#!/bin/bash
#PBS -N pipeline
#PBS -l ncpus=4
#PBS -l mem=48gb
#PBS -m abe
#PBS -M jtweedle@go.olemiss.edu

umask 007
cd $PBS_O_WORKDIR

#load the necessary modules
module load java
module load megahit

#set a file ID
ID="jake_B15"

#use trimmomatic script to trim the reads
java -jar /ddn/home6/bisc503/bin/Trimmomatic-0.38/trimmomatic-0.38.jar PE -phred33 \
../class07_08/${ID}_forward.fq.gz ../class07_08/${ID}_reverse.fq.gz \
./${ID}_R1_trim.fq.gz ./${ID}_R1_trim_unpaired.fq.gz \
./${ID}_R2_trim.fq.gz ./${ID}_R2_trim_unpaired.fq.gz \
ILLUMINACLIP:/ddn/home6/bisc503/bin/Trimmomatic-0.38/adapters/NexteraPE-PE.fa:2:30:10


#sickle is used to remove reads or sequence ends that don't meet a baseline quality score i.e Phred scores
sickle pe -f ${ID}_R1_trim.fq.gz -r ${ID}_R2_trim.fq.gz \
-t sanger -o ${ID}_R1_sickled-trim.fq -p ${ID}_R2_sickled-trim.fq \
-s ${ID}_sickle-trim_singletons.fq.gz

#megahit is used to assemble the clean, trimmed reads from sickle and compute some scaffold stats
megahit -1 ${ID}_R1_sickled-trim.fq -2 ${ID}_R2_sickled-trim.fq -o megahit_${ID}_out

~/bisc503/bin/bbmap/stats.sh in=megahit_${ID}_out \
gc=megahit_${ID}.gc gchist=megahit_${ID}.gchist shist=megahit_${ID}.shist \
> stats_megahit_${ID}



#sort scaffolds from megahit output into descending length order
~/bisc503/bin/bbmap/sortbyname.sh in=./megahit_jake_B15_out/final.contigs.fa out=final_sorted.fa length descending

#filter out scaffolds that are smaller than 10,000 bp (10 kb) in length
~/bisc503/bin/bbmap/filterbyname.sh in=final_sorted.fa out=filtered_10K.contigs.fa names=k  minlen=10000
