---
title: "3 Largest MS Universities"
author: "James Tweedle,Kevin Harrell, John McGregor"
date: "11/4/2019"
output: html_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(tidyverse)
library(maps)
library(htmltools)
library(leaflet)
```

```{r university}
ms_universities <- read.csv(textConnection(
  "Name, Mascot, Lat, Long
  Ole Miss, Landshark, 34.364865,-89.538454
  MSU, Bulldog,  33.455112,-88.794259
  Southern Miss, Golden Eagle, 31.330131,-89.334074"
))
universitylabel <- sprintf("<font size=5><b>%s</b></font>",ms_universities$Name) %>% 
  lapply(htmltools::HTML)
universtypopup <- sprintf("<font color='blue'><b>%s</b><br>%s</font>",ms_universities$Name,ms_universities$Mascot) %>% 
  lapply(htmltools::HTML)
ms_universities %>% 
  leaflet(options=leafletOptions(zoomsnap=0.1)) %>% 
  setView(lng=-89.3985,lat=32.3547,zoom=10) %>% 
  addTiles() %>% 
  addMarkers(~Long,~Lat,popup=universtypopup,label=universitylabel)
  